# Set variables once
variables:
  solutionType: DotNetCore # angularDotNetCore, dotNetCore, angular
  apiDirectory: ''
  coverletCoverageExclusions: ''

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: janisBerz/azure-devops-templates
    endpoint: 'janisBerz'
    ref: refs/new-job
    

trigger:
- master
pr:
- master

jobs:
- template: jobs/dotNetCore.yml.yml@azureDevOpsTemplates # Template reference
  parameters:
    coverletCoverageExclusions: $(coverletCoverageExclusions)
    apiDirectory: $(apiDirectory)